title: Tyler Etters — Biolink
description: ...to see a chlorophyll dawn.
baseurl: /
url: https://tyleretters.com
include: ['_pages']
tagline: Seasoned designer, developer, and leader.
blurb: I've spent half my life passionately building software and leading agency teams and clients. I am a seasoned consultant with countless products, solutions, and integrations deployed in both B2B and B2C domains. After serving as Vice President at Highland, I am seeking a full-time position on a remote team where I can focus on building software instead of a company. I am a citizen of the United States, vaccinated, and able to travel for work.
plugins:
  - jekyll-feed
  - jekyll-redirect-from
include: ['_pages']