title: Tyler Etters — Biolink
description: ...to see a chlorophyll dawn.
baseurl: /
url: https://tyleretters.com
include: ['_pages']
tagline: Seasoned designer, developer, and leader.
blurb: Passionately building software since 2006 and compassionately leading agency teams and clients since 2012, I am a seasoned consultant with countless products, solutions, and integrations deployed in both B2B and B2C domains. After serving as Vice President at Highland for two years (and being with the agency for a total of eight), I am seeking a full-time position on a remote team where I can build software with my own hands. I am a citizen of the United States, vaccinated, and able to travel for work.